### ISSUE TITLE
Explore "Wiki" github repo tab

### ISSUE THREAD

**Issue by theamarks** [nceas-coding-club/nceas-coding-club.github.io#10]
Issues are a great place to capture actionable tasks, but may not be the best spot for our team meeting notes. May the Wiki tab? I don't know anything about it, but might make more sense. Let's explore?!

**Comment by camilavargasp** [comment]
Loving the wiki!
Just transferred all the meeting notes to [a wiki](https://github.com/nceas-coding-club/nceas-coding-club.github.io/wiki/Meeting-Notes#thursday-august-11).
