### ISSUE TITLE
For loops can sequence through non-number sequences

### ISSUE THREAD

**Issue by theamarks** [nceas-coding-club/nceas-coding-club.github.io#20]
I did not know this until a couple of weeks ago. It blew my mind and allowed me to loop through designated column names. Not sure if this is a "best practice" but helped me have a deeper understanding of the function.

**Comment by njlyon0** [comment]
This is so fun! I'll tackle this data byte if that's okay with others

**Comment by njlyon0** [comment]
Created a first draft of this byte and submitted a pull request! See here: https://github.com/nceas-coding-club/nceas-coding-club.github.io/pull/21

**Comment by njlyon0** [comment]
Draft is merged so closing this issue now!
